Add bookings
Shelopuhina/java-shareit pull request #2
Opened 2023-11-20 22:10 UTC by Shelopuhina

В общем задавила меня работа и пришлось перейти в новую когорту) но зато теперь и вправду появилось время,так что наконец доделала этого франкенштейна:)

2023-12-05 10:06 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!bookingDtoIn.getEnd().isAfter(bookingDtoIn.getStart()))
проверку входных данных лучше сделать в начале метода, чтобы не дергать лишний раз БД в случае если входные данные кривые

2023-12-05 10:10 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Optional<User> userOpt = userStorage.findById(userId);
Можно красивей 
```
		userRepository.findById(userId)
				.orElseThrow(() -> new NotFoundException("Пользователь с id=" + userId + " не найден"));
```

2023-12-05 10:12 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +public interface BookingStorage extends JpaRepository<Booking, Integer> {
С этого момента уже слово Storage не используем, вместо него   BookingRepository

2023-12-05 10:19 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +
Еще добавь
	```
@ExceptionHandler
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}
```
В него попадут все оставшиеся не словленные в предыдущих методах

2023-12-05 10:21 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto updateItem(@PathVariable int itemId, @RequestBody ItemDto itemDto, @RequestHeader("X-Sharer-User-Id") int userId) {
Здесь нужно  добавить использование `@Validated(Update.class)`

` @RequestBody @Validated(Update.class) ItemDto item`

2023-12-05 10:33 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemStorage.findAllByOwnerIdOrderByIdAsc(userId).stream()
Не оптимально в цикле (stream.map) делать на каждый элемент запрос в БД.

Нужно постараться переделать: одним запросом получаем все item, затем одним запросом все комменты, потом их группируем и связываем между собой без доп запросов в БД

2023-12-05 10:38 UTC, VadimZharkov requested changes
Значительно лучше, чем было)
Можно улучшить.

2023-12-08 21:55 UTC, Shelopuhina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto updateItem(@PathVariable int itemId, @RequestBody ItemDto itemDto, @RequestHeader("X-Sharer-User-Id") int userId) {
я не знаю,как именно реализовать эту часть кода. Провела за этим несколько часов, столько статей,но безуспешно. Много где встречала информацпию, что это гнупповая валидация, валидация парамтеров запроса. И пыталась точечно эту инфу найти. но скорее больше данных по поводу просто @valid, ошибок вылетало немеренно. Если просто вставить вашу строку, то не работает. При чем я пыталась налажить путем добавления интерфейсов и присвоения аннотациям этих групп интерфейсов, пробовала правильно прописать ErrorHandler, дополнительно вводила методы. Но все впустую(

2023-12-09 12:10 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto updateItem(@PathVariable int itemId, @RequestBody ItemDto itemDto, @RequestHeader("X-Sharer-User-Id") int userId) {
Добавляем в проект пустой интерфейс или интерфейсы (если для create тоже есть желание сгруппировать валидацию полей класса)
```
public interface Update {
}
```

```
public interface Create {
}
```

Далее в классе расставляем аннотации, например для юзера могло бы так выглядеть
```
@Data
@AllArgsConstructor
public class UserDto {
	private Long id;

	@NotBlank(groups = {Create.class})
	private String name;

	@Email(groups = {Update.class, Create.class})
	@NotNull(groups = {Create.class})
	private String email;
}

```
и далее в контроллерах если нужно валидировать только помеченные поля используем

```
@PatchMapping("{userId}")
public UserDto update(@PathVariable long userId, @RequestBody @Validated(Update.class) UserDto userDto) {
		userDto.setId(userId);
		log.info("Updating user {}", userDto);
		return userService.updateUser(userDto);
	}
```

2023-12-09 12:16 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotNull
Если есть @NotEmpty то  @NotNull не нужен, т.к. он уже содержится в @NotEmpty

2023-12-09 12:18 UTC, VadimZharkov requested changes
По валидации попробуй еще, в комменте отписался что нужно сделать

2023-12-11 06:08 UTC, VadimZharkov approved these changes

2023-12-12 09:05 UTC, merged