Add bookings
Shelopuhina/java-shareit pull request #3
Opened 2023-12-16 01:50 UTC by Shelopuhina

2023-12-16 06:54 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        if (!(item.getRequest() == null)) {
можно в одну строку в бильдере
.requestId(item.getRequest() == null ? null :  item.getRequest().getId())

2023-12-16 07:01 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private Pageable getPageable(int from, int size) {
Во всех сервисах одинаковый метод Pageable getPageable(int from, int size)
Его нужно вынести в отдельный "утильный" класс
public final class PageUtils {
   public static Pageable getPageable(int from, int size) {
     ...
   }
}

2023-12-16 07:12 UTC, VadimZharkov commented on src/test/java/ru/practicum/shareit/ItemRepositoryTest.java
> +@DataJpaTest
@DataJpaTest относятся к интеграционным тестам (тестирование взаимодействия с  БД), поэтому можно смело в integrationTests поместить

2023-12-16 07:20 UTC, VadimZharkov requested changes
Можно улучшить, плюс в мок тестах достаточно часто используется конструкция verify
Попробуй ее тоже использовать
https://habr.com/ru/articles/444982/

2023-12-16 21:13 UTC, Shelopuhina commented
использовала в одном классе verify, чтобы попрактиковаться. Остальные замечания поправила,спасибо!<3

2023-12-17 08:05 UTC, VadimZharkov approved these changes

2023-12-20 22:29 UTC, merged