Add docker
Shelopuhina/java-shareit pull request #4
Opened 2023-12-23 18:17 UTC by Shelopuhina

2023-12-23 18:38 UTC, Shelopuhina commented
добрый вечер! отправила на проверку. Оказалось была проблема с LocalDateTime, т к я в мск и там вот вся эта история +0/+3.

2023-12-24 08:05 UTC, VadimZharkov commented on pom.xml
>      <dependencies>
Из родительского pom зависимости нужно убрать, т.к. они у каждого модуля свои. Например <groupId>com.h2database</groupId> в gateway не нужен

2023-12-24 08:08 UTC, VadimZharkov commented on gateway/src/main/java/ru/practicum/shareit/ShareItGateway.java
> +@PropertySource(ignoreResourceNotFound = true, value = "classpath:gateway/src/main/resources/application.properties")
Дефолтное размещение ресурсов. Поэтому лишнее прописывать дефолтное размещение.

2023-12-24 08:12 UTC, VadimZharkov commented on gateway/src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
Для всех прочих ошибок добавить
```
	@ExceptionHandler
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}
```

2023-12-24 08:13 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +}
То же замечание что и для gateway

2023-12-24 08:18 UTC, VadimZharkov commented on gateway/src/main/java/ru/practicum/shareit/booking/model/BookingDtoIn.java
> +package ru.practicum.shareit.booking.model;
В gateway моделей (сущностей сохраняемых в БД) нет. Поэтому название пакета не соответствует содержимому. Назови dto.

2023-12-24 08:23 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
Все методы @Transactional, поэтому можно эту аннотацию повесить на класс.
А лучше на класс повесить @Transactional(readOnly = true)
А на те методы, в которых есть запись в БД поставить @Transactional

2023-12-24 08:25 UTC, VadimZharkov requested changes
Можно улучшить.

2023-12-25 11:37 UTC, VadimZharkov approved these changes

2023-12-28 10:39 UTC, merged